#!/bin/python3
from http.server import SimpleHTTPRequestHandler
from socketserver import TCPServer
from webbrowser import open

PORT = 8000
handler = SimpleHTTPRequestHandler

with TCPServer(("", PORT), handler) as httpd:
    print("Iniciado el servidor de la app en el puerto: ", PORT)
    open(f"http://localhost:{PORT}")
    httpd.serve_forever()
